### ISSUE TITLE
The "=begin ~ =end " comment causes an error when the new line code is CR+LF.

### ISSUE THREAD

**Issue by noanoa07** [yhara/dxopal#4]
When I wrote a comment in my code using "=begin ~ =end", an error has occurred.
In this case it occurs only in the CR+LF new line code, and does not occur in the LF new line code. 
(the character code is UTF-8)

・Firefox, Safari/ macOS High Sierra
・Firefox/ Windows 7

**Comment by yhara** [comment]
This is fixed by upgrading Opal to 0.11.0 (I heard they rewrote the parser).
Will be fixed by the next release, DXOpal 1.1.0.
