### ISSUE TITLE
API reference displays a 404 page.

### ISSUE THREAD

**Issue by hiy** [yhara/dxopal#43]
Hi. I would like to see the API reference page below, but I get a 404 page.

https://yhara.github.io/dxopal/doc/api/DXOpal/Constants/Colors.html
https://yhara.github.io/dxopal/doc/api/DXOpal/Input/KeyCodes.html
https://yhara.github.io/dxopal/doc/api/DXOpal/Input/Touch.html

However, when I executed the following command on the local machine, it was output.

`yard doc -o doc/api/ lib/**/*.rb lib/**/**/*.rb`

Why doesn't it appear on the github page?

**Comment by yhara** [comment]
Oh I did not commit these files. Should be fixed by 45970f0.
