### ISSUE TITLE
z value of Window.draw () does not work

### ISSUE THREAD

**Issue by mieki256** [yhara/dxopal#7]
z value of Window.draw () does not work.

example.
http://blawat2015.no-ip.com/~mieki256/diary/201802241.html#201802241

I think

      sorted = @@draw_queue.sort{|a, b| a[0] == b[0] ? a[1] <=> b[1] : a[0] <=> a[1] }

->

      sorted = @@draw_queue.sort{|a, b| a[0] == b[0] ? a[1] <=> b[1] : a[0] <=> b[0] }

**Comment by yhara** [comment]
Oh that's right. Thanks!
